# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: inalix/website-hugo
  branch: main
  base_url: https://sve-auth.styawan.workers.dev

i18n:
  structure: multiple_folders
  locales: [en, id]

logo:
  src: logo_inalix_square_default.svg
  show_in_header: true

media_libraries:
  all:
    transformations:
      raster_image:
        format: webp
        quality: 85
        width: 1024
        height: 1024
      svg:
        optimize: true

media_folder: /public/media
public_folder: /media

collections:
  - name: projects
    label: Projects
    label_singular: Project
    folder: /content/{{locale}}/projects
    path: "{{slug}}/index"
    media_folder: images
    public_folder: images
    i18n: true
    fields:
      - { label: Title, name: title, widget: string, i18n: true }
      - { label: Draft, name: draft, widget: boolean, i18n: duplicate }
      - { label: Image, name: image, widget: image, multiple: false, i18n: duplicate }
      - { label: Meta Title, name: meta_title, widget: compute, value: '{{fields.title}} | INALIX', i18n: true }
      - { label: Description, name: description, widget: string, i18n: true }
      - { label: Categories, name: categories, widget: relation, collection: solution, search_fields: ["name"], value_field: "name", display_fields: ["name"], i18n: duplicate }
      
     # - { label: Categories, name: categories, widget: list, multiple: false, i18n: duplicate, default: ["Projects"] }
      - { label: Tags, name: tags, widget: list, multiple: true, i18n: duplicate, required: false }
      - { label: Author, name: author, widget: relation, collection: team, search_fields: ["name", "title"], value_field: "name", display_fields: ["name", "title"], i18n: duplicate } 
      - { label: Date, name: date, widget: datetime, type: date, i18n: duplicate }
      - { label: Location, name: location, widget: string, hint: 'Cth: Bali, Indonesia', required: false, i18n: duplicate }
      - { label: Client Name, name: client_name, widget: relation, collection: clients, search_fields: ["name"], value_field: "name", display_fields: ["name"], required: false, i18n: duplicate }
      - { label: Started Year, name: started, widget: string, hint: 'Cth: 2001', required: false, i18n: duplicate }
      - { label: Completed Year, name: completed, widget: string, hint: 'Cth: 2010', required: false, i18n: duplicate }
      - { label: Body, name: body, widget: richtext, i18n: true }
      
  - name: products
    label: Products
    label_singular: Product
    folder: /content/{{locale}}/products
    path: "{{slug}}/index"
    media_folder: images
    public_folder: images
    preview: false
    i18n: true
    fields:
      - { label: Title, name: title, widget: string, i18n: true }
      - { label: Slug, name: slug, widget: string, required: false, i18n: duplicate }
      - { label: Image, name: image, widget: image, i18n: duplicate }
     # - { label: Thumbnail, name: thumbnail, widget: image, i18n: duplicate }
      - { label: Meta Title, name: meta_title, widget: compute, value: '{{fields.title}} | INALIX', i18n: true }
      - { label: Description, name: description, widget: string, i18n: true }
      - { label: Date, name: date, widget: datetime, type: date, required: false, i18n: duplicate }
      - { label: Categories, name: categories, widget: list, multiple: false, i18n: duplicate, required: false }
      - { label: Tags, name: tags, widget: list, multiple: true, i18n: duplicate, required: false }
      - { label: Author, name: author, widget: relation, collection: team, search_fields: ["name", "title"], value_field: "name", display_fields: ["name", "title"], i18n: duplicate } 
      - { label: Body, name: body, widget: richtext, i18n: true }
   #  - { label: Gallery, name: gallery, widget: image, multiple: true, i18n: duplicate }
      

  - name: news
    label: News
    label_singular: News
    folder: /content/{{locale}}/news
    path: "{{slug}}/index"
    media_folder: images
    public_folder: images
    i18n: true
    fields:
      - { label: Title, name: title, widget: string, i18n: true }
      - { label: Draft, name: draft, widget: boolean, i18n: duplicate }
      - { label: Image, name: image, widget: image, multiple: false, i18n: duplicate }
      - { label: Meta Title, name: meta_title, widget: compute, value: '{{fields.title}} | INALIX', i18n: true }
      - { label: Description, name: description, widget: string, i18n: true }
      - { label: Categories, name: categories, widget: list, multiple: false, i18n: duplicate, default: ["News"] }
      - { label: Tags, name: tags, widget: list, multiple: true, i18n: duplicate, required: false }
      - { label: Author, name: author, widget: relation, collection: team, search_fields: ["name", "title"], value_field: "name", display_fields: ["name", "title"], i18n: duplicate } 
      - { label: Solution, name: solution, widget: relation, collection: solution, search_fields: ["name"], value_field: "name", display_fields: ["name"], i18n: duplicate }
      - { label: Date, name: date, widget: datetime, type: date, i18n: duplicate }
      - { label: Update Date, name: date_update, widget: datetime, type: date, required: false, i18n: duplicate }
      - { label: Body, name: body, widget: richtext, i18n: true }

  - name: pages
    label: Pages
    label_singular: Page
    i18n: true
    files:
      - name: about
        label: About Us
        file: content/{{locale}}/pages/about.md
        # media_folder: images
        # public_folder: images
        i18n: true
        fields:
          - { label: Main Page Title, name: title, widget: string, default: About Us, i18n: true }
          - { label: Type, name: type, widget: string, default: about, required: false, i18n: duplicate }
          - { label: Layout, name: layout, widget: string, default: list, required: false, i18n: duplicate }
          - { label: Company Logo, name: logo, widget: image, required: false, i18n: duplicate }
          - { label: History Header Image, name: history_image, widget: image, required: false, i18n: duplicate }
          - { label: History Title, name: history_title, widget: string, default: History Inalix, i18n: true }
          - { label: History Content Text, name: body, widget: markdown, i18n: true }
          - label: Work Culture Banner
            name: culture_banner
            widget: object
            i18n: true
            fields:
              - { label: Banner Title, name: title, widget: string, i18n: true }
              - { label: Description, name: text, widget: text, i18n: true }
              - label: Image Slider Gallery
                name: images
                widget: list
                fields: 
                  - { label: Image, name: image, widget: image, i18n: duplicate}

          - { label: Values Section Title, name: values_title, widget: string, default: Our commitment is our values., i18n: true }
          - label: Company Values List
            name: values
            widget: list
            i18n: true
            fields:
              - { label: Value Title, name: title, widget: string, i18n: true }
              - { label: Icon Class, name: icon, widget: string, i18n: duplicate }
              - { label: Explanation Description, name: description, widget: text, i18n: true }

          - { label: Solution Section Title, name: solution_title, widget: string, default: Got a problem? We can give you the solution, i18n: true }
          - { label: Solution Description, name: solution_text, widget: text, i18n: true }

          - { label: Quote Banner, name: banner_quote, widget: string, i18n: true }

          - label: FAQ List
            name: faqs
            widget: list
            i18n: true
            fields:
              - { label: Question, name: question, widget: string, i18n: true }
              - { label: Answer, name: answer, widget: markdown, i18n: true }

          - label: Right Sidebar Card
            name: sidebar_card
            widget: object
            i18n: true
            fields:
              - { label: Card Title, name: title, widget: string, default: OPERATIONAL EXCELLENCE, i18n: true }
              - { label: Icon Class, name: icon, widget: string, default: stmicon-notebook_b, i18n: duplicate }
              - { label: Description, name: text, widget: text, i18n: true }
              - { label: Background Image, name: bg_image, widget: image, required: false, i18n: duplicate }

      

      - name: privacy-policy
        label: Privacy Policy
        file: content/{{locale}}/pages/privacy-policy.md
        i18n: true
        fields:
          - { label: Title, name: title, widget: string, i18n: true }
          - { label: Meta Title, name: meta_title, widget: compute, value: '{{fields.title}} | INALIX', i18n: true }
          - { label: Description, name: description, widget: string, required: false, i18n: true }
          - { label: Draft, name: draft, widget: boolean, i18n: duplicate }
          - { label: Body, name: body, widget: richtext, i18n: true }

      - name: contact
        label: Contact Us
        file: content/{{locale}}/pages/contact.md
        i18n: true
        fields:
          - { label: Title, name: title, widget: string, default: Contact Us, i18n: true }
          - label: Offices List
            name: offices
            widget: list
            i18n: true
            fields:
              - { label: Office, name: office, widget: relation, collection: office, search_fields: ["name"], value_field: '{{slug}}', display_fields: ["name"], i18n: duplicate }
      

  - name: office
    label: Offices
    label_singular: Office
    identifier_field: name
    folder: content/{{locale}}/office
    path: "{{slug}}/index"
    i18n: true
    fields:
      - { label: Name, name: name, widget: string, hint: "Ex: Head Office", i18n: duplicate }
      - { label: Draft, name: draft, widget: boolean, default: false, i18n: duplicate }
      - { label: Address, name: address, widget: richtext, i18n: duplicate }
      - { label: Location, name: location, widget: string, i18n: duplicate }
      - { label: Point Location, name: point, widget: map, required: false, i18n: duplicate}
      - { label: Phone Number, name: phone, widget: string, required: false, i18n: duplicate }
      - { label: Email Address, name: email, widget: string, required: false, i18n: duplicate }
      - { label: Operational Hours, name: hours, widget: string, required: false, i18n: duplicate }
      - { label: Icon, name: icon, widget: string, required: false, i18n: duplicate}
  
  - name: division
    label: Divisions
    label_singular: division
    identifier_field: name
    folder: /content/{{locale}}/division
    preview: false
    i18n: true
    fields:
      - { label: Name Division, name: name, widget: string, i18n: duplicate }

  - name: team
    label: Teams
    identifier_field: name
    label_singular: team
    folder: /content/{{locale}}/team
    path: "{{slug}}/index"
    media_folder: images
    public_folder: images
    i18n: true
    fields:
      - { label: Name, name: name, widget: string, i18n: duplicate }
      - { label: Profile Picture, name: photo, widget: image, i18n: duplicate }
      - { label: Job Title, name: title, widget: string, i18n: duplicate }
      - { label: Division, name: division, widget: relation, collection: division, default: "project", search_fields: ["name"], value_field: "{{slug}}", display_fields: ["name"], i18n: duplicate }
      - { label: Office, name: office, widget: relation, collection: office, search_fields: ["name"], value_field: '{{slug}}', display_fields: ["name"], i18n: duplicate }
      - { label: Draft, name: draft, widget: boolean, default: false, i18n: duplicate }
      - { label: Body, name: body, widget: richtext, required: false, i18n: duplicate }

  - name: clients
    label: Clients 
    identifier_field: name
    label_singular: client
    folder: /content/{{locale}}/clients
    path: "{{slug}}/index"
    media_folder: images
    public_folder: images
    preview: false
    i18n: true
    fields:
      - { label: Name, name: name, widget: string, i18n: duplicate }
      - { label: Address, name: address, widget: richtext, i18n: duplicate }
      - { label: Image, name: image, widget: image, required: true, i18n: duplicate }
      - { label: Draft, name: draft, widget: boolean, default: false, i18n: duplicate }

  
  - name: solution
    label: Solutions
    label_singular: Solution
    identifier_field: name
    folder: /content/{{locale}}/solution
    preview: false
    i18n: true
    fields:
      - { label: Solution Name, name: name, widget: string, i18n: duplicate }
